project: 
  type: website
  output-dir: docs

website:
  title: "Vincent Nguyen's Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        file: aboutme.qmd
      - text: "Projects"
        menu:
          - text: "Starter Analysis Exercise"
            file: starter-analysis-exercise/products/report/starter-analysis-report.qmd
          - text: "R Coding Exercise"
            file: coding-exercise/coding-exercise.qmd
          - text: "Week 4 Data Exercise"
            file: data-exercise/data-exercise.qmd
          - text: "Data Presentation Exercise"
            file: presentation-exercise/presentation-exercise.qmd
          - text: "CDC Data Exercise"
            file: cdcdata-exercise/cdcdata-exercise.qmd
          - text: "Fitting Exercise"
            file: fitting-exercise/fitting-exercise.qmd
          - text: "Machine Learning"
            file: ml-models-exercise/ml-models-exercise.qmd
    right:
      - icon: github 
        href: https://github.com/vlnt2677/vincentnguyen-MADA-portfolio       
format:
  html:
    theme: sketchy
    highlight: zenburn
    css: styles.css
    toc: FALSE